### ISSUE TITLE
Spin-up a local cdmr server for use in development

### ISSUE THREAD

**Issue by lesserwhirls** [lesserwhirls/cdm-rpc#7]
Need to extend Gradle to start and stop a local `cdmr` server for developing/testing client code against.

It also looks like we will need a `grpc-web` proxy to translate the normal HTTP requests from the JavaScript client to the gRPC service and to respond with something the browser can understand:

https://grpc.io/blog/state-of-grpc-web/#the-tech

It looks like the Envoy proxy is the way to go, which can be run using Docker.

The easiest path might be to spin up a docker container with both `cdmr` and the Envoy proxy. Gradle can manage this as long as Docker is available. Again, probably the easiest, especially since we are just testing.

Thoughts @jtroberts?

Longer-term, there is a [gRPC-web in-process proxy](https://github.com/grpc/grpc-web/blob/master/src/connector/README.md#java-grpc-web-in-process-proxy) that can be added to a Java based gRPC service that would eliminate the need to run a separate proxy. For now, I think it's best to keep them separate

**Comment by jtroberts** [comment]
Using Docker containers sound good to me.
